app:
    name: order-service
    env: dev
server:
    host: localhost
    port: 8001
database:
    name: db
    host: localhost
    port: 5436
    ssl: disable
    user: user
    password: password
    timezone: UTC
    connection:
        idle: 10
        open: 100
messaging:
    protocol: amqp
    host: localhost
    port: 5672
    user: guest
    password: guest
    order:
        exchange:
            name: order-exchange
            type: direct
        queue: orders
discovery:
    server:
        host: localhost
        port: 8500
logging:
    level: debug
